name: font_asset
description: A class for font assets to be used in Flutter for the hook system.
version: 0.0.3
repository: https://github.com/mosuem/font_asset

environment:
  sdk: ^3.10.0

dependencies:
  hooks: ^1.0.0

dev_dependencies:
  dart_flutter_team_lints: ^3.5.2
  lints: ^6.0.0
  test: ^1.25.6
