name: font_asset
description: A starting point for Dart libraries or applications.
version: 0.0.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

dependencies:
  hooks: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
